### ISSUE TITLE
Set up assesment branch

### ISSUE THREAD

**Issue by hannes-ha** [hannes-ha/DD2480-Assignment2#14]

**Comment by tayloh** [comment]
The "assessment" branch is currently branched off of an older version of the code (test-push) that I have tested and should work for demonstration

This canvas post explains what the "assessment" branch: https://canvas.kth.se/courses/37918/discussion_topics/297483
"usually contain a somewhat recent copy of the CI server itself, but it can also be unrelated code"

We can update the assessment branch by merging main into it and get a more recent version later if we want. Just need to make sure we know how to demonstrate using that version of the code (e.g. "modify and temporarily break the unit tests", or push unfinished code that doesn't compile).
